// مصدر الكلمات — مفاتيح مختصرة: e=english, a=arabic, p=partOfSpeech,
// ex=exampleEnglish, exa=exampleArabic, d=difficulty(1..3), c=category.
// المولّد يتحقق من عدم التكرار ويرتّب حسب الصعوبة ويكتب js/data/words.js.
// ملاحظة: تُتجنّب الفواصل العليا (') في الإنجليزية لتبسيط النطق للمبتدئ.

export const words = [
  // ===== ضمائر وكلمات وظيفية =====
  { e: 'I', a: 'أنا', p: 'ضمير', ex: 'I am a student.', exa: 'أنا طالب.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'you', a: 'أنتَ / أنتِ', p: 'ضمير', ex: 'You are my friend.', exa: 'أنت صديقي.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'he', a: 'هو', p: 'ضمير', ex: 'He is a teacher.', exa: 'هو معلم.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'she', a: 'هي', p: 'ضمير', ex: 'She is here.', exa: 'هي هنا.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'it', a: 'هو/هي (لغير العاقل)', p: 'ضمير', ex: 'It is a big dog.', exa: 'إنه كلب كبير.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'we', a: 'نحن', p: 'ضمير', ex: 'We are friends.', exa: 'نحن أصدقاء.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'they', a: 'هم / هنّ', p: 'ضمير', ex: 'They are at home.', exa: 'هم في المنزل.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'this', a: 'هذا / هذه', p: 'اسم إشارة', ex: 'This is my book.', exa: 'هذا كتابي.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'that', a: 'ذلك / تلك', p: 'اسم إشارة', ex: 'That is a car.', exa: 'تلك سيارة.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'these', a: 'هؤلاء / هذه', p: 'اسم إشارة', ex: 'These are my keys.', exa: 'هذه مفاتيحي.', d: 2, c: 'ضمائر وكلمات وظيفية' },
  { e: 'those', a: 'أولئك / تلك', p: 'اسم إشارة', ex: 'Those are big houses.', exa: 'تلك منازل كبيرة.', d: 2, c: 'ضمائر وكلمات وظيفية' },
  { e: 'who', a: 'مَن', p: 'أداة استفهام', ex: 'Who is that man?', exa: 'مَن ذلك الرجل؟', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'what', a: 'ماذا / ما', p: 'أداة استفهام', ex: 'What is this?', exa: 'ما هذا؟', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'where', a: 'أين', p: 'أداة استفهام', ex: 'Where is my bag?', exa: 'أين حقيبتي؟', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'when', a: 'متى', p: 'أداة استفهام', ex: 'When do we start?', exa: 'متى نبدأ؟', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'why', a: 'لماذا', p: 'أداة استفهام', ex: 'Why are you sad?', exa: 'لماذا أنت حزين؟', d: 2, c: 'ضمائر وكلمات وظيفية' },
  { e: 'how', a: 'كيف', p: 'أداة استفهام', ex: 'How do you feel?', exa: 'كيف تشعر؟', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'which', a: 'أيّ', p: 'أداة استفهام', ex: 'Which one do you want?', exa: 'أيّ واحد تريد؟', d: 2, c: 'ضمائر وكلمات وظيفية' },
  { e: 'and', a: 'و', p: 'حرف عطف', ex: 'Tea and coffee.', exa: 'شاي وقهوة.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'or', a: 'أو', p: 'حرف عطف', ex: 'Tea or coffee?', exa: 'شاي أم قهوة؟', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'but', a: 'لكن', p: 'حرف عطف', ex: 'I am tired but happy.', exa: 'أنا متعب لكن سعيد.', d: 2, c: 'ضمائر وكلمات وظيفية' },
  { e: 'because', a: 'لأنّ', p: 'أداة ربط', ex: 'I am late because of traffic.', exa: 'تأخرت بسبب الزحام.', d: 2, c: 'ضمائر وكلمات وظيفية' },
  { e: 'with', a: 'مع', p: 'حرف جر', ex: 'Come with me.', exa: 'تعال معي.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'without', a: 'بدون', p: 'حرف جر', ex: 'Tea without sugar.', exa: 'شاي بدون سكر.', d: 2, c: 'ضمائر وكلمات وظيفية' },
  { e: 'for', a: 'لـ / من أجل', p: 'حرف جر', ex: 'This gift is for you.', exa: 'هذه الهدية لك.', d: 2, c: 'ضمائر وكلمات وظيفية' },
  { e: 'from', a: 'من', p: 'حرف جر', ex: 'I am from Egypt.', exa: 'أنا من مصر.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'to', a: 'إلى', p: 'حرف جر', ex: 'I go to school.', exa: 'أذهب إلى المدرسة.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'in', a: 'في', p: 'حرف جر', ex: 'The keys are in the bag.', exa: 'المفاتيح في الحقيبة.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'on', a: 'على', p: 'حرف جر', ex: 'The book is on the table.', exa: 'الكتاب على الطاولة.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'under', a: 'تحت', p: 'حرف جر', ex: 'The cat is under the chair.', exa: 'القط تحت الكرسي.', d: 2, c: 'ضمائر وكلمات وظيفية' },
  { e: 'not', a: 'ليس / لا', p: 'أداة نفي', ex: 'I am not ready.', exa: 'أنا لست جاهزًا.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'very', a: 'جدًا', p: 'ظرف', ex: 'It is very hot today.', exa: 'الجو حار جدًا اليوم.', d: 1, c: 'ضمائر وكلمات وظيفية' },
  { e: 'also', a: 'أيضًا', p: 'ظرف', ex: 'I want water also.', exa: 'أريد ماءً أيضًا.', d: 2, c: 'ضمائر وكلمات وظيفية' },
  { e: 'maybe', a: 'ربما', p: 'ظرف', ex: 'Maybe tomorrow.', exa: 'ربما غدًا.', d: 2, c: 'ضمائر وكلمات وظيفية' },

  // ===== الأرقام =====
  { e: 'one', a: 'واحد', p: 'عدد', ex: 'I have one brother.', exa: 'لديّ أخ واحد.', d: 1, c: 'الأرقام' },
  { e: 'two', a: 'اثنان', p: 'عدد', ex: 'I have two cats.', exa: 'لديّ قطتان.', d: 1, c: 'الأرقام' },
  { e: 'three', a: 'ثلاثة', p: 'عدد', ex: 'Three cups of tea.', exa: 'ثلاثة أكواب شاي.', d: 1, c: 'الأرقام' },
  { e: 'four', a: 'أربعة', p: 'عدد', ex: 'Four people are here.', exa: 'أربعة أشخاص هنا.', d: 1, c: 'الأرقام' },
  { e: 'five', a: 'خمسة', p: 'عدد', ex: 'Five minutes, please.', exa: 'خمس دقائق من فضلك.', d: 1, c: 'الأرقام' },
  { e: 'six', a: 'ستة', p: 'عدد', ex: 'I wake up at six.', exa: 'أستيقظ الساعة السادسة.', d: 1, c: 'الأرقام' },
  { e: 'seven', a: 'سبعة', p: 'عدد', ex: 'Seven days in a week.', exa: 'سبعة أيام في الأسبوع.', d: 1, c: 'الأرقام' },
  { e: 'eight', a: 'ثمانية', p: 'عدد', ex: 'The shop opens at eight.', exa: 'يفتح المتجر الساعة الثامنة.', d: 1, c: 'الأرقام' },
  { e: 'nine', a: 'تسعة', p: 'عدد', ex: 'Nine students passed.', exa: 'نجح تسعة طلاب.', d: 1, c: 'الأرقام' },
  { e: 'ten', a: 'عشرة', p: 'عدد', ex: 'I need ten dollars.', exa: 'أحتاج عشرة دولارات.', d: 1, c: 'الأرقام' },
  { e: 'eleven', a: 'أحد عشر', p: 'عدد', ex: 'The bus comes at eleven.', exa: 'تأتي الحافلة الساعة الحادية عشرة.', d: 2, c: 'الأرقام' },
  { e: 'twelve', a: 'اثنا عشر', p: 'عدد', ex: 'Twelve months in a year.', exa: 'اثنا عشر شهرًا في السنة.', d: 2, c: 'الأرقام' },
  { e: 'twenty', a: 'عشرون', p: 'عدد', ex: 'I am twenty years old.', exa: 'عمري عشرون عامًا.', d: 2, c: 'الأرقام' },
  { e: 'thirty', a: 'ثلاثون', p: 'عدد', ex: 'Thirty days in the month.', exa: 'ثلاثون يومًا في الشهر.', d: 2, c: 'الأرقام' },
  { e: 'fifty', a: 'خمسون', p: 'عدد', ex: 'The book has fifty pages.', exa: 'الكتاب فيه خمسون صفحة.', d: 2, c: 'الأرقام' },
  { e: 'hundred', a: 'مئة', p: 'عدد', ex: 'One hundred people came.', exa: 'جاء مئة شخص.', d: 2, c: 'الأرقام' },
  { e: 'thousand', a: 'ألف', p: 'عدد', ex: 'A thousand words.', exa: 'ألف كلمة.', d: 3, c: 'الأرقام' },
  { e: 'first', a: 'الأول', p: 'ترتيبي', ex: 'This is my first day.', exa: 'هذا يومي الأول.', d: 2, c: 'الأرقام' },
  { e: 'second', a: 'الثاني', p: 'ترتيبي', ex: 'Take the second street.', exa: 'خذ الشارع الثاني.', d: 2, c: 'الأرقام' },
  { e: 'last', a: 'الأخير', p: 'صفة', ex: 'This is the last one.', exa: 'هذا هو الأخير.', d: 2, c: 'الأرقام' },
  { e: 'number', a: 'رقم', p: 'اسم', ex: 'What is your number?', exa: 'ما رقمك؟', d: 2, c: 'الأرقام' },
  { e: 'half', a: 'نصف', p: 'اسم', ex: 'Half an hour.', exa: 'نصف ساعة.', d: 2, c: 'الأرقام' },
  // ===== الأفعال الأساسية =====
  { e: 'go', a: 'يذهب', p: 'فعل', ex: 'I go to work early.', exa: 'أذهب إلى العمل مبكرًا.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'come', a: 'يأتي', p: 'فعل', ex: 'Please come here.', exa: 'من فضلك تعال هنا.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'eat', a: 'يأكل', p: 'فعل', ex: 'We eat lunch at noon.', exa: 'نأكل الغداء عند الظهر.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'drink', a: 'يشرب', p: 'فعل', ex: 'I drink water every day.', exa: 'أشرب الماء كل يوم.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'want', a: 'يريد', p: 'فعل', ex: 'I want to sleep.', exa: 'أريد أن أنام.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'have', a: 'يملك / لديه', p: 'فعل', ex: 'I have a question.', exa: 'لديّ سؤال.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'make', a: 'يصنع / يجعل', p: 'فعل', ex: 'I make tea in the morning.', exa: 'أصنع الشاي في الصباح.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'do', a: 'يفعل', p: 'فعل', ex: 'What do you do?', exa: 'ماذا تعمل؟', d: 1, c: 'الأفعال الأساسية' },
  { e: 'say', a: 'يقول', p: 'فعل', ex: 'Say it again, please.', exa: 'قلها مرة أخرى من فضلك.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'see', a: 'يرى', p: 'فعل', ex: 'I can see the sea.', exa: 'أستطيع رؤية البحر.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'look', a: 'ينظر', p: 'فعل', ex: 'Look at this picture.', exa: 'انظر إلى هذه الصورة.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'hear', a: 'يسمع', p: 'فعل', ex: 'I hear a strange sound.', exa: 'أسمع صوتًا غريبًا.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'listen', a: 'يستمع', p: 'فعل', ex: 'Listen to the teacher.', exa: 'استمع إلى المعلم.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'speak', a: 'يتحدّث', p: 'فعل', ex: 'I speak a little English.', exa: 'أتحدث الإنجليزية قليلًا.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'talk', a: 'يتكلّم / يتحادث', p: 'فعل', ex: 'We talk every evening.', exa: 'نتحدث كل مساء.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'read', a: 'يقرأ', p: 'فعل', ex: 'I read before sleeping.', exa: 'أقرأ قبل النوم.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'write', a: 'يكتب', p: 'فعل', ex: 'Write your name here.', exa: 'اكتب اسمك هنا.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'learn', a: 'يتعلّم', p: 'فعل', ex: 'I want to learn English.', exa: 'أريد أن أتعلم الإنجليزية.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'know', a: 'يعرف', p: 'فعل', ex: 'I know the answer.', exa: 'أعرف الإجابة.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'understand', a: 'يفهم', p: 'فعل', ex: 'I do not understand.', exa: 'أنا لا أفهم.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'think', a: 'يفكّر / يظنّ', p: 'فعل', ex: 'I think it is a good idea.', exa: 'أظن أنها فكرة جيدة.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'feel', a: 'يشعر', p: 'فعل', ex: 'I feel very happy.', exa: 'أشعر بسعادة كبيرة.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'like', a: 'يحبّ / يعجبه', p: 'فعل', ex: 'I like this song.', exa: 'تعجبني هذه الأغنية.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'love', a: 'يحبّ (حبًّا شديدًا)', p: 'فعل', ex: 'I love my family.', exa: 'أحب عائلتي.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'need', a: 'يحتاج', p: 'فعل', ex: 'I need some help.', exa: 'أحتاج بعض المساعدة.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'help', a: 'يساعد', p: 'فعل', ex: 'Can you help me?', exa: 'هل يمكنك مساعدتي؟', d: 1, c: 'الأفعال الأساسية' },
  { e: 'work', a: 'يعمل', p: 'فعل', ex: 'I work in a hospital.', exa: 'أعمل في مستشفى.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'play', a: 'يلعب', p: 'فعل', ex: 'The children play outside.', exa: 'يلعب الأطفال في الخارج.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'sleep', a: 'ينام', p: 'فعل', ex: 'I sleep eight hours.', exa: 'أنام ثماني ساعات.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'sit', a: 'يجلس', p: 'فعل', ex: 'Please sit down.', exa: 'من فضلك اجلس.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'stand', a: 'يقف', p: 'فعل', ex: 'Please stand up.', exa: 'من فضلك قف.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'walk', a: 'يمشي', p: 'فعل', ex: 'I walk to school.', exa: 'أمشي إلى المدرسة.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'run', a: 'يجري', p: 'فعل', ex: 'He can run fast.', exa: 'يستطيع الجري بسرعة.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'open', a: 'يفتح', p: 'فعل', ex: 'Open the window, please.', exa: 'افتح النافذة من فضلك.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'close', a: 'يغلق', p: 'فعل', ex: 'Please close the door.', exa: 'من فضلك أغلق الباب.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'buy', a: 'يشتري', p: 'فعل', ex: 'I want to buy this.', exa: 'أريد أن أشتري هذا.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'sell', a: 'يبيع', p: 'فعل', ex: 'They sell fresh fruit.', exa: 'يبيعون فاكهة طازجة.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'pay', a: 'يدفع', p: 'فعل', ex: 'I will pay now.', exa: 'سأدفع الآن.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'give', a: 'يعطي', p: 'فعل', ex: 'Give me the book, please.', exa: 'أعطني الكتاب من فضلك.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'take', a: 'يأخذ', p: 'فعل', ex: 'Take this bag.', exa: 'خذ هذه الحقيبة.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'put', a: 'يضع', p: 'فعل', ex: 'Put it on the table.', exa: 'ضعه على الطاولة.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'get', a: 'يحصل على', p: 'فعل', ex: 'I want to get a job.', exa: 'أريد الحصول على وظيفة.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'find', a: 'يجد', p: 'فعل', ex: 'I cannot find my keys.', exa: 'لا أستطيع إيجاد مفاتيحي.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'start', a: 'يبدأ', p: 'فعل', ex: 'We start at nine.', exa: 'نبدأ الساعة التاسعة.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'stop', a: 'يتوقّف', p: 'فعل', ex: 'The bus stops here.', exa: 'تتوقف الحافلة هنا.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'finish', a: 'ينهي', p: 'فعل', ex: 'I finish work at five.', exa: 'أنهي العمل الساعة الخامسة.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'use', a: 'يستخدم', p: 'فعل', ex: 'I use my phone a lot.', exa: 'أستخدم هاتفي كثيرًا.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'call', a: 'يتّصل / ينادي', p: 'فعل', ex: 'Call me tonight.', exa: 'اتصل بي الليلة.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'ask', a: 'يسأل', p: 'فعل', ex: 'Ask the teacher.', exa: 'اسأل المعلم.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'answer', a: 'يجيب', p: 'فعل', ex: 'Please answer the question.', exa: 'من فضلك أجب عن السؤال.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'wait', a: 'ينتظر', p: 'فعل', ex: 'Wait for me here.', exa: 'انتظرني هنا.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'meet', a: 'يقابل', p: 'فعل', ex: 'Let us meet tomorrow.', exa: 'لنلتقِ غدًا.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'live', a: 'يعيش / يسكن', p: 'فعل', ex: 'I live in a big city.', exa: 'أعيش في مدينة كبيرة.', d: 1, c: 'الأفعال الأساسية' },
  { e: 'leave', a: 'يغادر / يترك', p: 'فعل', ex: 'I leave home at eight.', exa: 'أغادر المنزل الساعة الثامنة.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'arrive', a: 'يصل', p: 'فعل', ex: 'We arrive at noon.', exa: 'نصل عند الظهر.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'drive', a: 'يقود', p: 'فعل', ex: 'I drive to work.', exa: 'أقود السيارة إلى العمل.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'bring', a: 'يُحضِر', p: 'فعل', ex: 'Bring your book, please.', exa: 'أحضر كتابك من فضلك.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'send', a: 'يرسل', p: 'فعل', ex: 'Send me a message.', exa: 'أرسل لي رسالة.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'show', a: 'يُظهِر / يُري', p: 'فعل', ex: 'Show me the way.', exa: 'أرِني الطريق.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'tell', a: 'يخبر', p: 'فعل', ex: 'Tell me the truth.', exa: 'أخبرني بالحقيقة.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'try', a: 'يحاول', p: 'فعل', ex: 'Try again, please.', exa: 'حاول مرة أخرى من فضلك.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'remember', a: 'يتذكّر', p: 'فعل', ex: 'I remember your name.', exa: 'أتذكر اسمك.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'forget', a: 'ينسى', p: 'فعل', ex: 'Do not forget the keys.', exa: 'لا تنسَ المفاتيح.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'wash', a: 'يغسل', p: 'فعل', ex: 'Wash your hands.', exa: 'اغسل يديك.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'cook', a: 'يطبخ', p: 'فعل', ex: 'My mother cooks well.', exa: 'أمي تطبخ جيدًا.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'watch', a: 'يشاهد', p: 'فعل', ex: 'We watch a film tonight.', exa: 'نشاهد فيلمًا الليلة.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'wear', a: 'يرتدي', p: 'فعل', ex: 'I wear a coat in winter.', exa: 'أرتدي معطفًا في الشتاء.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'carry', a: 'يحمل', p: 'فعل', ex: 'Can you carry this box?', exa: 'هل يمكنك حمل هذا الصندوق؟', d: 3, c: 'الأفعال الأساسية' },
  { e: 'change', a: 'يغيّر', p: 'فعل', ex: 'I want to change my seat.', exa: 'أريد تغيير مقعدي.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'move', a: 'يتحرّك / ينتقل', p: 'فعل', ex: 'Please do not move.', exa: 'من فضلك لا تتحرك.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'turn', a: 'يستدير / يُدير', p: 'فعل', ex: 'Turn left at the corner.', exa: 'استدر يسارًا عند الزاوية.', d: 2, c: 'الأفعال الأساسية' },
  { e: 'build', a: 'يبني', p: 'فعل', ex: 'They build new houses.', exa: 'يبنون منازل جديدة.', d: 3, c: 'الأفعال الأساسية' },
  { e: 'hope', a: 'يأمل / يتمنّى', p: 'فعل', ex: 'I hope you are well.', exa: 'أتمنّى أن تكون بخير.', d: 3, c: 'الأفعال الأساسية' },

  // ===== الصفات الأساسية =====
  { e: 'big', a: 'كبير', p: 'صفة', ex: 'This is a big house.', exa: 'هذا منزل كبير.', d: 1, c: 'الصفات الأساسية' },
  { e: 'small', a: 'صغير', p: 'صفة', ex: 'I have a small bag.', exa: 'لديّ حقيبة صغيرة.', d: 1, c: 'الصفات الأساسية' },
  { e: 'good', a: 'جيّد', p: 'صفة', ex: 'This is a good idea.', exa: 'هذه فكرة جيدة.', d: 1, c: 'الصفات الأساسية' },
  { e: 'bad', a: 'سيّئ', p: 'صفة', ex: 'The weather is bad today.', exa: 'الطقس سيئ اليوم.', d: 1, c: 'الصفات الأساسية' },
  { e: 'new', a: 'جديد', p: 'صفة', ex: 'I bought a new phone.', exa: 'اشتريت هاتفًا جديدًا.', d: 1, c: 'الصفات الأساسية' },
  { e: 'old', a: 'قديم / كبير في السن', p: 'صفة', ex: 'This is an old book.', exa: 'هذا كتاب قديم.', d: 1, c: 'الصفات الأساسية' },
  { e: 'hot', a: 'حارّ / ساخن', p: 'صفة', ex: 'The tea is very hot.', exa: 'الشاي حار جدًا.', d: 1, c: 'الصفات الأساسية' },
  { e: 'cold', a: 'بارد', p: 'صفة', ex: 'The water is cold.', exa: 'الماء بارد.', d: 1, c: 'الصفات الأساسية' },
  { e: 'fast', a: 'سريع', p: 'صفة', ex: 'This is a fast car.', exa: 'هذه سيارة سريعة.', d: 1, c: 'الصفات الأساسية' },
  { e: 'slow', a: 'بطيء', p: 'صفة', ex: 'The internet is slow.', exa: 'الإنترنت بطيء.', d: 2, c: 'الصفات الأساسية' },
  { e: 'easy', a: 'سهل', p: 'صفة', ex: 'This lesson is easy.', exa: 'هذا الدرس سهل.', d: 1, c: 'الصفات الأساسية' },
  { e: 'difficult', a: 'صعب', p: 'صفة', ex: 'The exam was difficult.', exa: 'كان الامتحان صعبًا.', d: 2, c: 'الصفات الأساسية' },
  { e: 'long', a: 'طويل', p: 'صفة', ex: 'It is a long road.', exa: 'إنه طريق طويل.', d: 1, c: 'الصفات الأساسية' },
  { e: 'short', a: 'قصير', p: 'صفة', ex: 'This is a short story.', exa: 'هذه قصة قصيرة.', d: 1, c: 'الصفات الأساسية' },
  { e: 'tall', a: 'طويل القامة', p: 'صفة', ex: 'He is a tall man.', exa: 'هو رجل طويل.', d: 2, c: 'الصفات الأساسية' },
  { e: 'high', a: 'عالٍ / مرتفع', p: 'صفة', ex: 'The mountain is very high.', exa: 'الجبل مرتفع جدًا.', d: 2, c: 'الصفات الأساسية' },
  { e: 'cheap', a: 'رخيص', p: 'صفة', ex: 'This shirt is cheap.', exa: 'هذا القميص رخيص.', d: 2, c: 'الصفات الأساسية' },
  { e: 'expensive', a: 'غالٍ / باهظ', p: 'صفة', ex: 'The hotel is expensive.', exa: 'الفندق غالٍ.', d: 2, c: 'الصفات الأساسية' },
  { e: 'clean', a: 'نظيف', p: 'صفة', ex: 'The room is clean.', exa: 'الغرفة نظيفة.', d: 1, c: 'الصفات الأساسية' },
  { e: 'dirty', a: 'متّسخ', p: 'صفة', ex: 'My shoes are dirty.', exa: 'حذائي متسخ.', d: 2, c: 'الصفات الأساسية' },
  { e: 'full', a: 'ممتلئ', p: 'صفة', ex: 'The bus is full.', exa: 'الحافلة ممتلئة.', d: 2, c: 'الصفات الأساسية' },
  { e: 'empty', a: 'فارغ', p: 'صفة', ex: 'The bottle is empty.', exa: 'الزجاجة فارغة.', d: 2, c: 'الصفات الأساسية' },
  { e: 'heavy', a: 'ثقيل', p: 'صفة', ex: 'This box is heavy.', exa: 'هذا الصندوق ثقيل.', d: 2, c: 'الصفات الأساسية' },
  { e: 'strong', a: 'قويّ', p: 'صفة', ex: 'He is very strong.', exa: 'هو قوي جدًا.', d: 2, c: 'الصفات الأساسية' },
  { e: 'weak', a: 'ضعيف', p: 'صفة', ex: 'I feel weak today.', exa: 'أشعر بالضعف اليوم.', d: 3, c: 'الصفات الأساسية' },
  { e: 'beautiful', a: 'جميل', p: 'صفة', ex: 'What a beautiful garden!', exa: 'يا لها من حديقة جميلة!', d: 2, c: 'الصفات الأساسية' },
  { e: 'nice', a: 'لطيف / جميل', p: 'صفة', ex: 'She is a nice person.', exa: 'هي شخص لطيف.', d: 1, c: 'الصفات الأساسية' },
  { e: 'kind', a: 'طيّب / لطيف', p: 'صفة', ex: 'He is very kind.', exa: 'هو طيب جدًا.', d: 2, c: 'الصفات الأساسية' },
  { e: 'ready', a: 'جاهز', p: 'صفة', ex: 'I am ready now.', exa: 'أنا جاهز الآن.', d: 2, c: 'الصفات الأساسية' },
  { e: 'busy', a: 'مشغول', p: 'صفة', ex: 'I am busy today.', exa: 'أنا مشغول اليوم.', d: 2, c: 'الصفات الأساسية' },
  { e: 'free', a: 'متفرّغ / مجاني', p: 'صفة', ex: 'Are you free tomorrow?', exa: 'هل أنت متفرّغ غدًا؟', d: 2, c: 'الصفات الأساسية' },
  { e: 'important', a: 'مهمّ', p: 'صفة', ex: 'This is an important day.', exa: 'هذا يوم مهم.', d: 2, c: 'الصفات الأساسية' },
  { e: 'right', a: 'صحيح / يمين', p: 'صفة', ex: 'Your answer is right.', exa: 'إجابتك صحيحة.', d: 1, c: 'الصفات الأساسية' },
  { e: 'wrong', a: 'خطأ', p: 'صفة', ex: 'This answer is wrong.', exa: 'هذه الإجابة خطأ.', d: 2, c: 'الصفات الأساسية' },
  { e: 'same', a: 'نفس / متماثل', p: 'صفة', ex: 'We have the same bag.', exa: 'لدينا نفس الحقيبة.', d: 2, c: 'الصفات الأساسية' },
  { e: 'different', a: 'مختلف', p: 'صفة', ex: 'They are very different.', exa: 'هما مختلفان جدًا.', d: 2, c: 'الصفات الأساسية' },
  { e: 'near', a: 'قريب', p: 'صفة', ex: 'The shop is near my house.', exa: 'المتجر قريب من منزلي.', d: 2, c: 'الصفات الأساسية' },
  { e: 'far', a: 'بعيد', p: 'صفة', ex: 'The airport is far.', exa: 'المطار بعيد.', d: 2, c: 'الصفات الأساسية' },
  { e: 'early', a: 'مبكّر', p: 'صفة', ex: 'I wake up early.', exa: 'أستيقظ مبكرًا.', d: 2, c: 'الصفات الأساسية' },
  { e: 'late', a: 'متأخّر', p: 'صفة', ex: 'Sorry, I am late.', exa: 'آسف، أنا متأخر.', d: 2, c: 'الصفات الأساسية' },
  { e: 'young', a: 'صغير السن', p: 'صفة', ex: 'She is a young girl.', exa: 'هي فتاة صغيرة.', d: 2, c: 'الصفات الأساسية' },
  { e: 'rich', a: 'غنيّ', p: 'صفة', ex: 'He is a rich man.', exa: 'هو رجل غني.', d: 3, c: 'الصفات الأساسية' },
  { e: 'poor', a: 'فقير', p: 'صفة', ex: 'They help poor families.', exa: 'يساعدون العائلات الفقيرة.', d: 3, c: 'الصفات الأساسية' },
  { e: 'quiet', a: 'هادئ', p: 'صفة', ex: 'The street is quiet.', exa: 'الشارع هادئ.', d: 3, c: 'الصفات الأساسية' },
  { e: 'loud', a: 'مرتفع الصوت', p: 'صفة', ex: 'The music is too loud.', exa: 'الموسيقى مرتفعة جدًا.', d: 3, c: 'الصفات الأساسية' },
  { e: 'safe', a: 'آمن', p: 'صفة', ex: 'This place is safe.', exa: 'هذا المكان آمن.', d: 3, c: 'الصفات الأساسية' },
  { e: 'delicious', a: 'لذيذ', p: 'صفة', ex: 'The food is delicious.', exa: 'الطعام لذيذ.', d: 2, c: 'الصفات الأساسية' },
  { e: 'sweet', a: 'حلو', p: 'صفة', ex: 'This juice is sweet.', exa: 'هذا العصير حلو.', d: 2, c: 'الصفات الأساسية' },
  { e: 'hungry', a: 'جائع', p: 'صفة', ex: 'I am very hungry.', exa: 'أنا جائع جدًا.', d: 1, c: 'الصفات الأساسية' },
  { e: 'thirsty', a: 'عطشان', p: 'صفة', ex: 'The child is thirsty.', exa: 'الطفل عطشان.', d: 2, c: 'الصفات الأساسية' },

  // ===== الألوان =====
  { e: 'color', a: 'لون', p: 'اسم', ex: 'What is your favorite color?', exa: 'ما لونك المفضّل؟', d: 2, c: 'الألوان' },
  { e: 'red', a: 'أحمر', p: 'صفة', ex: 'I have a red car.', exa: 'لديّ سيارة حمراء.', d: 1, c: 'الألوان' },
  { e: 'blue', a: 'أزرق', p: 'صفة', ex: 'The sky is blue.', exa: 'السماء زرقاء.', d: 1, c: 'الألوان' },
  { e: 'green', a: 'أخضر', p: 'صفة', ex: 'The tree is green.', exa: 'الشجرة خضراء.', d: 1, c: 'الألوان' },
  { e: 'yellow', a: 'أصفر', p: 'صفة', ex: 'The sun looks yellow.', exa: 'تبدو الشمس صفراء.', d: 1, c: 'الألوان' },
  { e: 'black', a: 'أسود', p: 'صفة', ex: 'I wear black shoes.', exa: 'أرتدي حذاءً أسود.', d: 1, c: 'الألوان' },
  { e: 'white', a: 'أبيض', p: 'صفة', ex: 'She has a white dress.', exa: 'لديها فستان أبيض.', d: 1, c: 'الألوان' },
  { e: 'brown', a: 'بنّي', p: 'صفة', ex: 'The bread is brown.', exa: 'الخبز بنّي.', d: 2, c: 'الألوان' },
  { e: 'orange', a: 'برتقالي', p: 'صفة', ex: 'I like the orange color.', exa: 'أحب اللون البرتقالي.', d: 2, c: 'الألوان' },
  { e: 'pink', a: 'وردي', p: 'صفة', ex: 'She has a pink bag.', exa: 'لديها حقيبة وردية.', d: 2, c: 'الألوان' },
  { e: 'gray', a: 'رمادي', p: 'صفة', ex: 'The sky is gray today.', exa: 'السماء رمادية اليوم.', d: 2, c: 'الألوان' },

  // ===== الأشخاص والعائلة =====
  { e: 'family', a: 'عائلة', p: 'اسم', ex: 'I love my family.', exa: 'أحب عائلتي.', d: 1, c: 'الأشخاص والعائلة' },
  { e: 'friend', a: 'صديق', p: 'اسم', ex: 'She is my best friend.', exa: 'هي أعز صديقاتي.', d: 1, c: 'الأشخاص والعائلة' },
  { e: 'mother', a: 'أم', p: 'اسم', ex: 'My mother is a teacher.', exa: 'أمي معلمة.', d: 1, c: 'الأشخاص والعائلة' },
  { e: 'father', a: 'أب', p: 'اسم', ex: 'His father works here.', exa: 'أبوه يعمل هنا.', d: 1, c: 'الأشخاص والعائلة' },
  { e: 'brother', a: 'أخ', p: 'اسم', ex: 'I have one brother.', exa: 'لديّ أخ واحد.', d: 1, c: 'الأشخاص والعائلة' },
  { e: 'sister', a: 'أخت', p: 'اسم', ex: 'My sister is a doctor.', exa: 'أختي طبيبة.', d: 1, c: 'الأشخاص والعائلة' },
  { e: 'son', a: 'ابن', p: 'اسم', ex: 'Their son is at school.', exa: 'ابنهم في المدرسة.', d: 2, c: 'الأشخاص والعائلة' },
  { e: 'daughter', a: 'ابنة', p: 'اسم', ex: 'My daughter likes books.', exa: 'ابنتي تحب الكتب.', d: 2, c: 'الأشخاص والعائلة' },
  { e: 'baby', a: 'رضيع', p: 'اسم', ex: 'The baby is sleeping.', exa: 'الرضيع نائم.', d: 1, c: 'الأشخاص والعائلة' },
  { e: 'child', a: 'طفل', p: 'اسم', ex: 'The child is playing.', exa: 'الطفل يلعب.', d: 1, c: 'الأشخاص والعائلة' },
  { e: 'man', a: 'رجل', p: 'اسم', ex: 'The man is tall.', exa: 'الرجل طويل.', d: 1, c: 'الأشخاص والعائلة' },
  { e: 'woman', a: 'امرأة', p: 'اسم', ex: 'The woman is a nurse.', exa: 'المرأة ممرضة.', d: 1, c: 'الأشخاص والعائلة' },
  { e: 'boy', a: 'ولد', p: 'اسم', ex: 'The boy is happy.', exa: 'الولد سعيد.', d: 1, c: 'الأشخاص والعائلة' },
  { e: 'girl', a: 'فتاة', p: 'اسم', ex: 'The girl is reading.', exa: 'الفتاة تقرأ.', d: 1, c: 'الأشخاص والعائلة' },
  { e: 'people', a: 'أشخاص / ناس', p: 'اسم', ex: 'Many people are here.', exa: 'كثير من الناس هنا.', d: 2, c: 'الأشخاص والعائلة' },
  { e: 'person', a: 'شخص', p: 'اسم', ex: 'He is a kind person.', exa: 'هو شخص طيب.', d: 2, c: 'الأشخاص والعائلة' },
  { e: 'husband', a: 'زوج', p: 'اسم', ex: 'Her husband is a driver.', exa: 'زوجها سائق.', d: 2, c: 'الأشخاص والعائلة' },
  { e: 'wife', a: 'زوجة', p: 'اسم', ex: 'His wife is a teacher.', exa: 'زوجته معلمة.', d: 2, c: 'الأشخاص والعائلة' },
  { e: 'name', a: 'اسم', p: 'اسم', ex: 'What is your name?', exa: 'ما اسمك؟', d: 1, c: 'الأشخاص والعائلة' },
  { e: 'neighbor', a: 'جار', p: 'اسم', ex: 'My neighbor is friendly.', exa: 'جاري ودود.', d: 3, c: 'الأشخاص والعائلة' },

  // ===== المنزل =====
  { e: 'house', a: 'منزل', p: 'اسم', ex: 'This is my house.', exa: 'هذا منزلي.', d: 1, c: 'المنزل' },
  { e: 'home', a: 'بيت / المنزل', p: 'اسم', ex: 'I am at home now.', exa: 'أنا في المنزل الآن.', d: 1, c: 'المنزل' },
  { e: 'room', a: 'غرفة', p: 'اسم', ex: 'The room is clean.', exa: 'الغرفة نظيفة.', d: 1, c: 'المنزل' },
  { e: 'door', a: 'باب', p: 'اسم', ex: 'Please close the door.', exa: 'من فضلك أغلق الباب.', d: 1, c: 'المنزل' },
  { e: 'window', a: 'نافذة', p: 'اسم', ex: 'Open the window, please.', exa: 'افتح النافذة من فضلك.', d: 1, c: 'المنزل' },
  { e: 'table', a: 'طاولة', p: 'اسم', ex: 'The food is on the table.', exa: 'الطعام على الطاولة.', d: 1, c: 'المنزل' },
  { e: 'chair', a: 'كرسي', p: 'اسم', ex: 'Sit on the chair.', exa: 'اجلس على الكرسي.', d: 1, c: 'المنزل' },
  { e: 'bed', a: 'سرير', p: 'اسم', ex: 'The bed is very soft.', exa: 'السرير ناعم جدًا.', d: 1, c: 'المنزل' },
  { e: 'kitchen', a: 'مطبخ', p: 'اسم', ex: 'My mother is in the kitchen.', exa: 'أمي في المطبخ.', d: 2, c: 'المنزل' },
  { e: 'bathroom', a: 'حمّام', p: 'اسم', ex: 'Where is the bathroom?', exa: 'أين الحمّام؟', d: 2, c: 'المنزل' },
  { e: 'floor', a: 'أرضية / طابق', p: 'اسم', ex: 'The floor is clean.', exa: 'الأرضية نظيفة.', d: 2, c: 'المنزل' },
  { e: 'key', a: 'مفتاح', p: 'اسم', ex: 'I lost my key.', exa: 'فقدت مفتاحي.', d: 1, c: 'المنزل' },
  { e: 'clock', a: 'ساعة (حائط)', p: 'اسم', ex: 'The clock is on the wall.', exa: 'الساعة على الحائط.', d: 2, c: 'المنزل' },
  { e: 'bag', a: 'حقيبة', p: 'اسم', ex: 'This bag is heavy.', exa: 'هذه الحقيبة ثقيلة.', d: 1, c: 'المنزل' },
  { e: 'box', a: 'صندوق', p: 'اسم', ex: 'Put it in the box.', exa: 'ضعه في الصندوق.', d: 2, c: 'المنزل' },
  { e: 'cup', a: 'كوب', p: 'اسم', ex: 'A cup of tea, please.', exa: 'كوب شاي من فضلك.', d: 1, c: 'المنزل' },
  { e: 'plate', a: 'طبق', p: 'اسم', ex: 'The plate is empty.', exa: 'الطبق فارغ.', d: 2, c: 'المنزل' },
  { e: 'light', a: 'ضوء / نور', p: 'اسم', ex: 'Turn on the light.', exa: 'أشعل الضوء.', d: 2, c: 'المنزل' },
  { e: 'wall', a: 'جدار', p: 'اسم', ex: 'The wall is white.', exa: 'الجدار أبيض.', d: 2, c: 'المنزل' },
  { e: 'garden', a: 'حديقة', p: 'اسم', ex: 'We have a small garden.', exa: 'لدينا حديقة صغيرة.', d: 2, c: 'المنزل' },

  // ===== الطعام والشراب =====
  { e: 'food', a: 'طعام', p: 'اسم', ex: 'The food is delicious.', exa: 'الطعام لذيذ.', d: 1, c: 'الطعام والشراب' },
  { e: 'water', a: 'ماء', p: 'اسم', ex: 'I drink water every day.', exa: 'أشرب الماء كل يوم.', d: 1, c: 'الطعام والشراب' },
  { e: 'bread', a: 'خبز', p: 'اسم', ex: 'I buy fresh bread.', exa: 'أشتري خبزًا طازجًا.', d: 1, c: 'الطعام والشراب' },
  { e: 'rice', a: 'أرز', p: 'اسم', ex: 'We eat rice with chicken.', exa: 'نأكل الأرز مع الدجاج.', d: 2, c: 'الطعام والشراب' },
  { e: 'meat', a: 'لحم', p: 'اسم', ex: 'The meat is fresh.', exa: 'اللحم طازج.', d: 2, c: 'الطعام والشراب' },
  { e: 'chicken', a: 'دجاج', p: 'اسم', ex: 'I like grilled chicken.', exa: 'أحب الدجاج المشوي.', d: 2, c: 'الطعام والشراب' },
  { e: 'fish', a: 'سمك', p: 'اسم', ex: 'We eat fish on Friday.', exa: 'نأكل السمك يوم الجمعة.', d: 1, c: 'الطعام والشراب' },
  { e: 'egg', a: 'بيضة', p: 'اسم', ex: 'I eat an egg for breakfast.', exa: 'آكل بيضة في الفطور.', d: 1, c: 'الطعام والشراب' },
  { e: 'milk', a: 'حليب', p: 'اسم', ex: 'The baby drinks milk.', exa: 'الرضيع يشرب الحليب.', d: 1, c: 'الطعام والشراب' },
  { e: 'tea', a: 'شاي', p: 'اسم', ex: 'I drink tea in the morning.', exa: 'أشرب الشاي في الصباح.', d: 1, c: 'الطعام والشراب' },
  { e: 'coffee', a: 'قهوة', p: 'اسم', ex: 'I want a cup of coffee.', exa: 'أريد كوب قهوة.', d: 1, c: 'الطعام والشراب' },
  { e: 'juice', a: 'عصير', p: 'اسم', ex: 'This orange juice is sweet.', exa: 'عصير البرتقال هذا حلو.', d: 2, c: 'الطعام والشراب' },
  { e: 'sugar', a: 'سكّر', p: 'اسم', ex: 'Tea without sugar, please.', exa: 'شاي بدون سكر من فضلك.', d: 2, c: 'الطعام والشراب' },
  { e: 'salt', a: 'ملح', p: 'اسم', ex: 'The soup needs salt.', exa: 'الحساء يحتاج ملحًا.', d: 2, c: 'الطعام والشراب' },
  { e: 'fruit', a: 'فاكهة', p: 'اسم', ex: 'I eat fruit every day.', exa: 'آكل الفاكهة كل يوم.', d: 2, c: 'الطعام والشراب' },
  { e: 'apple', a: 'تفاحة', p: 'اسم', ex: 'This apple is red.', exa: 'هذه التفاحة حمراء.', d: 1, c: 'الطعام والشراب' },
  { e: 'banana', a: 'موزة', p: 'اسم', ex: 'The banana is yellow.', exa: 'الموزة صفراء.', d: 1, c: 'الطعام والشراب' },
  { e: 'vegetable', a: 'خضار', p: 'اسم', ex: 'Vegetables are healthy.', exa: 'الخضار صحية.', d: 3, c: 'الطعام والشراب' },
  { e: 'cheese', a: 'جبن', p: 'اسم', ex: 'I like bread and cheese.', exa: 'أحب الخبز والجبن.', d: 2, c: 'الطعام والشراب' },
  { e: 'breakfast', a: 'فطور', p: 'اسم', ex: 'Breakfast is ready.', exa: 'الفطور جاهز.', d: 2, c: 'الطعام والشراب' },
  { e: 'lunch', a: 'غداء', p: 'اسم', ex: 'We have lunch at noon.', exa: 'نتناول الغداء عند الظهر.', d: 2, c: 'الطعام والشراب' },
  { e: 'dinner', a: 'عشاء', p: 'اسم', ex: 'Dinner is at eight.', exa: 'العشاء الساعة الثامنة.', d: 2, c: 'الطعام والشراب' },
  { e: 'meal', a: 'وجبة', p: 'اسم', ex: 'It was a great meal.', exa: 'كانت وجبة رائعة.', d: 3, c: 'الطعام والشراب' },
  { e: 'restaurant', a: 'مطعم', p: 'اسم', ex: 'The restaurant is busy.', exa: 'المطعم مزدحم.', d: 2, c: 'الطعام والشراب' },

  // ===== الوقت والأيام =====
  { e: 'day', a: 'يوم', p: 'اسم', ex: 'Have a nice day.', exa: 'أتمنى لك يومًا سعيدًا.', d: 1, c: 'الوقت والأيام' },
  { e: 'today', a: 'اليوم', p: 'ظرف', ex: 'Today is Monday.', exa: 'اليوم هو الاثنين.', d: 1, c: 'الوقت والأيام' },
  { e: 'tomorrow', a: 'غدًا', p: 'ظرف', ex: 'See you tomorrow.', exa: 'أراك غدًا.', d: 1, c: 'الوقت والأيام' },
  { e: 'yesterday', a: 'أمس', p: 'ظرف', ex: 'I was busy yesterday.', exa: 'كنت مشغولًا أمس.', d: 2, c: 'الوقت والأيام' },
  { e: 'time', a: 'وقت', p: 'اسم', ex: 'What time is it?', exa: 'كم الساعة؟', d: 1, c: 'الوقت والأيام' },
  { e: 'now', a: 'الآن', p: 'ظرف', ex: 'I am busy now.', exa: 'أنا مشغول الآن.', d: 1, c: 'الوقت والأيام' },
  { e: 'hour', a: 'ساعة (زمن)', p: 'اسم', ex: 'I wait for one hour.', exa: 'أنتظر ساعة واحدة.', d: 2, c: 'الوقت والأيام' },
  { e: 'minute', a: 'دقيقة', p: 'اسم', ex: 'Wait one minute, please.', exa: 'انتظر دقيقة من فضلك.', d: 2, c: 'الوقت والأيام' },
  { e: 'week', a: 'أسبوع', p: 'اسم', ex: 'I work five days a week.', exa: 'أعمل خمسة أيام في الأسبوع.', d: 2, c: 'الوقت والأيام' },
  { e: 'month', a: 'شهر', p: 'اسم', ex: 'Next month I travel.', exa: 'الشهر القادم أسافر.', d: 2, c: 'الوقت والأيام' },
  { e: 'year', a: 'سنة / عام', p: 'اسم', ex: 'A year has twelve months.', exa: 'السنة فيها اثنا عشر شهرًا.', d: 2, c: 'الوقت والأيام' },
  { e: 'morning', a: 'صباح', p: 'اسم', ex: 'Good morning!', exa: 'صباح الخير!', d: 1, c: 'الوقت والأيام' },
  { e: 'evening', a: 'مساء', p: 'اسم', ex: 'Good evening!', exa: 'مساء الخير!', d: 2, c: 'الوقت والأيام' },
  { e: 'night', a: 'ليل', p: 'اسم', ex: 'Good night!', exa: 'تصبح على خير!', d: 1, c: 'الوقت والأيام' },
  { e: 'Sunday', a: 'الأحد', p: 'اسم', ex: 'I rest on Sunday.', exa: 'أستريح يوم الأحد.', d: 2, c: 'الوقت والأيام' },
  { e: 'Monday', a: 'الاثنين', p: 'اسم', ex: 'Work starts on Monday.', exa: 'يبدأ العمل يوم الاثنين.', d: 2, c: 'الوقت والأيام' },
  { e: 'Tuesday', a: 'الثلاثاء', p: 'اسم', ex: 'We meet on Tuesday.', exa: 'نلتقي يوم الثلاثاء.', d: 2, c: 'الوقت والأيام' },
  { e: 'Wednesday', a: 'الأربعاء', p: 'اسم', ex: 'The class is on Wednesday.', exa: 'الحصة يوم الأربعاء.', d: 3, c: 'الوقت والأيام' },
  { e: 'Thursday', a: 'الخميس', p: 'اسم', ex: 'I travel on Thursday.', exa: 'أسافر يوم الخميس.', d: 3, c: 'الوقت والأيام' },
  { e: 'Friday', a: 'الجمعة', p: 'اسم', ex: 'Friday is a holiday.', exa: 'الجمعة عطلة.', d: 2, c: 'الوقت والأيام' },
  { e: 'Saturday', a: 'السبت', p: 'اسم', ex: 'We shop on Saturday.', exa: 'نتسوّق يوم السبت.', d: 2, c: 'الوقت والأيام' },
  { e: 'weekend', a: 'عطلة نهاية الأسبوع', p: 'اسم', ex: 'Have a nice weekend.', exa: 'عطلة سعيدة.', d: 3, c: 'الوقت والأيام' },

  // ===== الأماكن =====
  { e: 'here', a: 'هنا', p: 'ظرف', ex: 'Come here, please.', exa: 'تعال هنا، من فضلك.', d: 1, c: 'الأماكن' },
  { e: 'there', a: 'هناك', p: 'ظرف', ex: 'The shop is over there.', exa: 'المتجر هناك.', d: 1, c: 'الأماكن' },
  { e: 'place', a: 'مكان', p: 'اسم', ex: 'This is a nice place.', exa: 'هذا مكان جميل.', d: 2, c: 'الأماكن' },
  { e: 'city', a: 'مدينة', p: 'اسم', ex: 'I live in a big city.', exa: 'أعيش في مدينة كبيرة.', d: 2, c: 'الأماكن' },
  { e: 'street', a: 'شارع', p: 'اسم', ex: 'The street is busy.', exa: 'الشارع مزدحم.', d: 2, c: 'الأماكن' },
  { e: 'road', a: 'طريق', p: 'اسم', ex: 'This road is long.', exa: 'هذا الطريق طويل.', d: 2, c: 'الأماكن' },
  { e: 'school', a: 'مدرسة', p: 'اسم', ex: 'The school is near.', exa: 'المدرسة قريبة.', d: 1, c: 'الأماكن' },
  { e: 'hospital', a: 'مستشفى', p: 'اسم', ex: 'She works in a hospital.', exa: 'هي تعمل في مستشفى.', d: 2, c: 'الأماكن' },
  { e: 'market', a: 'سوق', p: 'اسم', ex: 'I buy fruit at the market.', exa: 'أشتري الفاكهة من السوق.', d: 2, c: 'الأماكن' },
  { e: 'shop', a: 'متجر', p: 'اسم', ex: 'The shop opens at nine.', exa: 'يفتح المتجر الساعة التاسعة.', d: 1, c: 'الأماكن' },
  { e: 'hotel', a: 'فندق', p: 'اسم', ex: 'The hotel is clean.', exa: 'الفندق نظيف.', d: 2, c: 'الأماكن' },
  { e: 'airport', a: 'مطار', p: 'اسم', ex: 'The airport is far.', exa: 'المطار بعيد.', d: 2, c: 'الأماكن' },
  { e: 'station', a: 'محطة', p: 'اسم', ex: 'The train station is big.', exa: 'محطة القطار كبيرة.', d: 3, c: 'الأماكن' },
  { e: 'bank', a: 'بنك', p: 'اسم', ex: 'The bank is closed now.', exa: 'البنك مغلق الآن.', d: 2, c: 'الأماكن' },
  { e: 'park', a: 'حديقة عامة', p: 'اسم', ex: 'We walk in the park.', exa: 'نمشي في الحديقة.', d: 2, c: 'الأماكن' },
  { e: 'office', a: 'مكتب', p: 'اسم', ex: 'My office is on floor two.', exa: 'مكتبي في الطابق الثاني.', d: 2, c: 'الأماكن' },
  { e: 'country', a: 'بلد', p: 'اسم', ex: 'Egypt is a big country.', exa: 'مصر بلد كبير.', d: 2, c: 'الأماكن' },
  { e: 'village', a: 'قرية', p: 'اسم', ex: 'She lives in a village.', exa: 'هي تعيش في قرية.', d: 3, c: 'الأماكن' },
  { e: 'mosque', a: 'مسجد', p: 'اسم', ex: 'The mosque is near my home.', exa: 'المسجد قريب من منزلي.', d: 2, c: 'الأماكن' },
  { e: 'beach', a: 'شاطئ', p: 'اسم', ex: 'The children play on the beach.', exa: 'يلعب الأطفال على الشاطئ.', d: 3, c: 'الأماكن' },

  // ===== الصحة والجسم =====
  { e: 'head', a: 'رأس', p: 'اسم', ex: 'My head hurts.', exa: 'رأسي يؤلمني.', d: 1, c: 'الصحة العامة' },
  { e: 'hand', a: 'يد', p: 'اسم', ex: 'Wash your hands.', exa: 'اغسل يديك.', d: 1, c: 'الصحة العامة' },
  { e: 'eye', a: 'عين', p: 'اسم', ex: 'Her eyes are brown.', exa: 'عيناها بنّيّتان.', d: 1, c: 'الصحة العامة' },
  { e: 'ear', a: 'أذن', p: 'اسم', ex: 'My ear hurts.', exa: 'أذني تؤلمني.', d: 2, c: 'الصحة العامة' },
  { e: 'nose', a: 'أنف', p: 'اسم', ex: 'The baby has a small nose.', exa: 'للرضيع أنف صغير.', d: 2, c: 'الصحة العامة' },
  { e: 'mouth', a: 'فم', p: 'اسم', ex: 'Open your mouth, please.', exa: 'افتح فمك من فضلك.', d: 2, c: 'الصحة العامة' },
  { e: 'tooth', a: 'سِنّ', p: 'اسم', ex: 'My tooth hurts.', exa: 'سِنّي يؤلمني.', d: 2, c: 'الصحة العامة' },
  { e: 'foot', a: 'قدم', p: 'اسم', ex: 'My foot is cold.', exa: 'قدمي باردة.', d: 2, c: 'الصحة العامة' },
  { e: 'leg', a: 'ساق / رِجل', p: 'اسم', ex: 'He has a strong leg.', exa: 'لديه ساق قوية.', d: 2, c: 'الصحة العامة' },
  { e: 'arm', a: 'ذراع', p: 'اسم', ex: 'My arm is tired.', exa: 'ذراعي متعبة.', d: 2, c: 'الصحة العامة' },
  { e: 'hair', a: 'شعر', p: 'اسم', ex: 'She has long hair.', exa: 'لديها شعر طويل.', d: 2, c: 'الصحة العامة' },
  { e: 'heart', a: 'قلب', p: 'اسم', ex: 'The doctor checks my heart.', exa: 'يفحص الطبيب قلبي.', d: 3, c: 'الصحة العامة' },
  { e: 'doctor', a: 'طبيب', p: 'اسم', ex: 'I need a doctor.', exa: 'أحتاج إلى طبيب.', d: 2, c: 'الصحة العامة' },
  { e: 'nurse', a: 'ممرّض/ة', p: 'اسم', ex: 'The nurse is very kind.', exa: 'الممرّضة لطيفة جدًا.', d: 3, c: 'الصحة العامة' },
  { e: 'medicine', a: 'دواء', p: 'اسم', ex: 'Take this medicine daily.', exa: 'تناول هذا الدواء يوميًا.', d: 3, c: 'الصحة العامة' },
  { e: 'sick', a: 'مريض', p: 'صفة', ex: 'My son is sick today.', exa: 'ابني مريض اليوم.', d: 2, c: 'الصحة العامة' },
  { e: 'pain', a: 'ألم', p: 'اسم', ex: 'I have a pain in my back.', exa: 'أشعر بألم في ظهري.', d: 3, c: 'الصحة العامة' },
  { e: 'health', a: 'صحة', p: 'اسم', ex: 'Good health is important.', exa: 'الصحة الجيدة مهمة.', d: 3, c: 'الصحة العامة' },
  { e: 'body', a: 'جسم', p: 'اسم', ex: 'Water is good for the body.', exa: 'الماء مفيد للجسم.', d: 2, c: 'الصحة العامة' },
  { e: 'face', a: 'وجه', p: 'اسم', ex: 'Wash your face.', exa: 'اغسل وجهك.', d: 2, c: 'الصحة العامة' },

  // ===== المشاعر =====
  { e: 'happy', a: 'سعيد', p: 'صفة', ex: 'I am very happy.', exa: 'أنا سعيد جدًا.', d: 1, c: 'المشاعر' },
  { e: 'sad', a: 'حزين', p: 'صفة', ex: 'She looks sad today.', exa: 'تبدو حزينة اليوم.', d: 1, c: 'المشاعر' },
  { e: 'angry', a: 'غاضب', p: 'صفة', ex: 'Please do not be angry.', exa: 'من فضلك لا تغضب.', d: 2, c: 'المشاعر' },
  { e: 'afraid', a: 'خائف', p: 'صفة', ex: 'The child is afraid.', exa: 'الطفل خائف.', d: 3, c: 'المشاعر' },
  { e: 'tired', a: 'متعب', p: 'صفة', ex: 'I feel tired today.', exa: 'أشعر بالتعب اليوم.', d: 2, c: 'المشاعر' },
  { e: 'worried', a: 'قلق', p: 'صفة', ex: 'I am worried about the exam.', exa: 'أنا قلق بشأن الامتحان.', d: 3, c: 'المشاعر' },
  { e: 'bored', a: 'ضجِر / ملول', p: 'صفة', ex: 'The film was boring, I am bored.', exa: 'كان الفيلم مملًا، أنا أشعر بالملل.', d: 3, c: 'المشاعر' },
  { e: 'surprised', a: 'متفاجئ', p: 'صفة', ex: 'I am surprised to see you.', exa: 'أنا متفاجئ برؤيتك.', d: 3, c: 'المشاعر' },
  { e: 'proud', a: 'فخور', p: 'صفة', ex: 'I am proud of you.', exa: 'أنا فخور بك.', d: 3, c: 'المشاعر' },
  { e: 'feeling', a: 'شعور', p: 'اسم', ex: 'It is a nice feeling.', exa: 'إنه شعور جميل.', d: 3, c: 'المشاعر' },
  { e: 'glad', a: 'مسرور', p: 'صفة', ex: 'I am glad to help.', exa: 'يسعدني أن أساعد.', d: 3, c: 'المشاعر' },
  { e: 'sure', a: 'متأكّد', p: 'صفة', ex: 'Are you sure?', exa: 'هل أنت متأكّد؟', d: 2, c: 'المشاعر' },

  // ===== العمل =====
  { e: 'job', a: 'وظيفة', p: 'اسم', ex: 'I have a new job.', exa: 'لديّ وظيفة جديدة.', d: 2, c: 'العمل' },
  { e: 'money', a: 'مال', p: 'اسم', ex: 'I need some money.', exa: 'أحتاج بعض المال.', d: 2, c: 'العمل' },
  { e: 'computer', a: 'حاسوب', p: 'اسم', ex: 'I work on a computer.', exa: 'أعمل على الحاسوب.', d: 2, c: 'العمل' },
  { e: 'email', a: 'بريد إلكتروني', p: 'اسم', ex: 'I sent you an email.', exa: 'أرسلت لك بريدًا إلكترونيًا.', d: 3, c: 'العمل' },
  { e: 'boss', a: 'مدير / رئيس', p: 'اسم', ex: 'My boss is very busy.', exa: 'مديري مشغول جدًا.', d: 3, c: 'العمل' },

  // ===== الدراسة =====
  { e: 'student', a: 'طالب', p: 'اسم', ex: 'She is a good student.', exa: 'هي طالبة جيدة.', d: 1, c: 'الدراسة' },
  { e: 'teacher', a: 'معلّم', p: 'اسم', ex: 'The teacher is kind.', exa: 'المعلم لطيف.', d: 1, c: 'الدراسة' },
  { e: 'book', a: 'كتاب', p: 'اسم', ex: 'I read a good book.', exa: 'أقرأ كتابًا جيدًا.', d: 1, c: 'الدراسة' },
  { e: 'lesson', a: 'درس', p: 'اسم', ex: 'This lesson is easy.', exa: 'هذا الدرس سهل.', d: 2, c: 'الدراسة' },
  { e: 'question', a: 'سؤال', p: 'اسم', ex: 'I have a question.', exa: 'لديّ سؤال.', d: 2, c: 'الدراسة' },
  { e: 'pen', a: 'قلم', p: 'اسم', ex: 'Can I use your pen?', exa: 'هل يمكنني استخدام قلمك؟', d: 2, c: 'الدراسة' },

  // ===== السفر =====
  { e: 'travel', a: 'يسافر / سفر', p: 'فعل/اسم', ex: 'I love to travel.', exa: 'أحب السفر.', d: 2, c: 'السفر' },
  { e: 'trip', a: 'رحلة', p: 'اسم', ex: 'Have a nice trip!', exa: 'رحلة سعيدة!', d: 2, c: 'السفر' },
  { e: 'ticket', a: 'تذكرة', p: 'اسم', ex: 'I need a bus ticket.', exa: 'أحتاج تذكرة حافلة.', d: 2, c: 'السفر' },
  { e: 'car', a: 'سيارة', p: 'اسم', ex: 'My car is new.', exa: 'سيارتي جديدة.', d: 1, c: 'السفر' },
  { e: 'bus', a: 'حافلة', p: 'اسم', ex: 'I take the bus to work.', exa: 'أستقل الحافلة إلى العمل.', d: 1, c: 'السفر' },
  { e: 'train', a: 'قطار', p: 'اسم', ex: 'The train is fast.', exa: 'القطار سريع.', d: 2, c: 'السفر' },
  { e: 'plane', a: 'طائرة', p: 'اسم', ex: 'The plane is ready.', exa: 'الطائرة جاهزة.', d: 2, c: 'السفر' },

  // ===== التسوق =====
  { e: 'price', a: 'سعر', p: 'اسم', ex: 'What is the price?', exa: 'ما هو السعر؟', d: 2, c: 'التسوق' },
  { e: 'customer', a: 'زبون / عميل', p: 'اسم', ex: 'The customer is happy.', exa: 'الزبون سعيد.', d: 3, c: 'التسوق' },
  { e: 'size', a: 'مقاس / حجم', p: 'اسم', ex: 'What size do you want?', exa: 'أي مقاس تريد؟', d: 3, c: 'التسوق' },
  { e: 'cash', a: 'نقد / كاش', p: 'اسم', ex: 'I will pay in cash.', exa: 'سأدفع نقدًا.', d: 3, c: 'التسوق' },
  // @@APPEND@@
];
